### ISSUE TITLE
MapboxGL doesn't fill div vertically in Firefox.

### ISSUE THREAD

**Issue by hallahan** [earthrise-media/justice-map#11]
<img width="1406" alt="Screen Shot 2021-04-13 at 12 50 18 PM" src="https://user-images.githubusercontent.com/556367/114612350-e2bba180-9c56-11eb-9f69-516f49942a15.png">

macOS 11.2.3 (20D91)

Firefox 87.0 (64-bit)

**Comment by tmcw** [comment]
Okay, main issue here is that I hadn't configured Tailwind unused-css-elimination, which made the css file 300k. Enabled in #21, now the bundle is ~6kb and this issue does not crop up. Only rendering after CSS loads would be ideal, but this solution was good enough.
