### ISSUE TITLE
this block group with high index is not highlighted

### ISSUE THREAD

**Issue by mikelmaron** [earthrise-media/justice-map#18]
![image](https://user-images.githubusercontent.com/22896/117149675-6ca5e880-ad85-11eb-8e2d-1118bf9fd08a.png)

**Comment by tmcw** [comment]
This is definitely a data issue, the block-highlights layer is totally different than the dissolved layer:

![image](https://user-images.githubusercontent.com/32314/117209052-db099b80-adc3-11eb-8ea3-f1ae85225743.png)

The block-highlights layer appears to have overlapping geometries and different boundaries than the dissolve copy layer, so we can't expect this interaction pattern to work reliably.

**Comment by mikelmaron** [comment]
I should explain the layers in the Mapbox Style -- they aren't well labeled (and yes give them better labels later on)

*  `ejscreen-2020-ca-d-pm25-2-dissolve copy` or `dissolveLayer` contains dissolved polygons of neighboring block groups with similar index values. Meant for visualization at low zooms, this layer is present between zooms 0 and 11. It's also used for the hover popup at low zooms
* `cali-projected-6z3k79 copy` or `targetLayer` is block group level data of the index. this layer is present at zoom 9 and above. There's overlap with the dissolveLayer, so that there's a smooth visual transition. It's used for the hover popup at higher zooms.
* `tabblock2010-06-pophu-blockgr-biqw81` or `populationLayer` is used only to calculate population numbers. Opacity is zero. 
* `block-highlights` uses the same tileset source as `cali-projected-6z3k79 copy`. So at zoom 9 or above, expect the rendering, the popup, and the highlight to all have the same value.

Sorry for the confusing labels -- but does this make sense? Because `block-highlights` and `cali-projected-6z3k79 copy` use the same source, expect the rendering of the fill and the filtering of the boundary would match up.

**Comment by mikelmaron** [comment]
I think I spotted what's up. The [min / max domain value for the slider is set to -15000/15000](https://github.com/earthrise-media/justice-map/blob/main/components/chart.tsx#L71). So block groups that exceed will always be excluded by the filter. The range of D_PM25_2 is the (arbitrary seeming) -18063.444039 <> 61,374
